### ISSUE TITLE
Load Vue routes dynamically

### ISSUE THREAD

**Issue by petarjs** [ivebe/handytools#1]
There is an option to define the routes in the backend, for example in a `.json` file, and to load them into Vue app dynamically, something like this:

```js
      router.addRoutes([{
        path: '/test',
        name: 'Test',
        component: require('./components/Test'),
      }]);
```

So if there was a service to load the routes from API, we'd have something like:

```js
routesApiService
  .getRoutes()
  .then(routes => {
    const transformedRoutes = routes.map(route => ({
      path: route.path,
      name: route.name,
      component: require(route.componentPath)
    }))
    
    router.addRoutes(transformedRoutes)
  })
```

`router.addRoutes` was added to VueRouter recently - http://stackoverflow.com/a/42476612 - pretty cool to be able to dynamically load routes!

**Comment by ivebe** [comment]
@petarjs Awesome thanks for insights. Would you like to make a PR, or you want someone else to do it?

**Comment by petarjs** [comment]
I'd like to, just need to find some time :) probably over the weekend :D

**Comment by ivebe** [comment]
I was not able to require component part dynamically, all sources I could find would point me to making static list of components. I believe that issue is that require works on compile time, so it can't accept variable that would be fetched from API. In the end I resolved it by creating routes.js files from backend during tool creation. So now there's no need for manually editing routes.js it will work with artisan, the same way tools creation does. 276cd824305880eb4dda3b2449ed2d10714a6b91
